Enabled: <true|false>
Output Dir: <dir>
Git:
  email: 
  name: 
SCServer: 127.0.0.1:25500
SCServerRemote: api.wcc.best # remote subconverter server for quanx config.
Storage: <url> # where proxies store.
Template: ./template/clash # where template store.
ProxyProviders:
#  <name1>: <url1>
#  <name2>: <url2>
# ...
ClashProviders:
  target: clash
  # belows are args provided to subconverter.
  list: true
  udp: true
  emoji: true
  sort: true
  #
QuantumultXRemotes: 
  target: quanx
  list: true
Exclude: # exclude proxies matched by below expression.
  All: <regexp> # proxies in 'All' proxies-group. 
  region: <regexp> # proxies in all-regions proxies groups.
#Exclude Args: # not a must-leave field.
#  syntax: 奈飞小铺|过期时间|剩余流量|官网|机场|维护 # regular expression that is given to subsconverter.
#  whitelist: 
#  - <provider1>
#  - <provider2>
#  ...
QuickGenQX: <true|false> # generate config by subconverter with its template.
SmartFilter: 
## Examples:
#  provider1: \d*\.*\d+(?:x|X|倍|倍率)
#  provider2: \d*\.*\d+(?:x|X|倍|倍率)|限速|Game|游戏|原生|IEPL|IPLC # Sequences matter.
##
Rules:
  Clash:
  # belows could be url(http/https) or file path on the system. 
    head: template/clash/head.yml
    rules: template/clash/connershua/rules.yml 